### ISSUE TITLE
Scheduled database backups

### ISSUE THREAD

**Issue by matushorvath** [matushorvath/aoc-bot#454]
Here is a CloudFormation YAML snippet that will schedule a daily backup of one DynamoDB table, with 35 day retention period:

```
Resources:
  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties: 
      BackupPlanName: DailyDynamoDBBackup
      Rules:
        - RuleName: DailyBackupRule 
          TargetBackupVault: (default backup vault)
          ScheduleExpression: "cron(0 12 * * ? *)" 
          StartWindowMinutes: 60
          CompletionWindowMinutes: 180
          Lifecycle:
            DeleteAfterDays: 35
```

This snippet:
- Creates a backup plan called "DailyDynamoDBBackup"
- Adds a backup rule called "DailyBackupRule"
- Schedules the backup to run daily at 12:00 PM
- Allows backups to start within a 1 hour window and complete within 3 hours
- Deletes backups after 35 days
